sudo: required

dist: trusty
  
language: php

php:
  - 7.1
  - 7.0
  - 5.6
  - nightly
  
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly
    
branches:
  only:
    - developer
   
services:
  - mysql
  
mysql:
  database: yetiforce
  username: root
  encoding: utf8
  
before_script:
- |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then
        sudo wget https://phar.phpunit.de/phpunit-5.7.phar
        sudo chmod +x phpunit-5.7.phar
        sudo mv phpunit-5.7.phar /usr/local/bin/phpunit
    else
        sudo wget https://phar.phpunit.de/phpunit-6.2.phar
        sudo chmod +x phpunit-6.2.phar
        sudo mv phpunit-6.2.phar /usr/local/bin/phpunit
    fi
- /usr/local/bin/phpunit --version
- composer install --no-dev
- sudo wget https://scrutinizer-ci.com/ocular.phar
- sudo chmod +x ocular.phar
- sudo mv ocular.phar /usr/local/bin/ocular
- mysql -e "SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION'"
- mysql -e "create database IF NOT EXISTS yetiforce;" -uroot
- cp tests/config.inc.txt config/config.inc.php
- cp tests/debug.txt config/debug.php
- cp tests/developer.txt config/developer.php
- cp tests/.htaccess .htaccess
  
script:
- cd tests
- /usr/local/bin/phpunit --debug --verbose --coverage-text --coverage-clover=coverage.xml
    
after_script:
- cd ..
- cat tests/LoginPage.txt
- cat tests/DetailView.txt
- cat tests/EditView.txt
- cat tests/ListView.txt
- cat tests/records.log
- cat cache/logs/errors.log
- cat cache/logs/request.log
- cat cache/logs/phpError.log
- cat cache/logs/system.log
- cat cache/logs/Importer.log
- php ocular code-coverage:upload --format=php-clover coverage.xml
- bash <(curl -s https://codecov.io/bash) 
